$dependenciesFile = "formatted_dependencies.txt"
$dependenciesCsvFile = "formatted_dependencies.csv"
$licensesFile = "sbom-licenses.txt"
$outputFile = "sbom-result.txt"
$csvOutputFile = "sbom-result.csv"

# Column widths
$dependencyWidth = 50
$currentVersionWidth = 15
$latestVersionWidth = 15
$dependencyTypeWidth = 18
$licenseWidth = 25
$licenseUrlWidth = 60

###############################################################################
# TXT HEADER
###############################################################################

$header = "{0}{1}{2}{3}{4}{5}" -f `
    "Dependency".PadRight($dependencyWidth), `
    "Current Version".PadRight($currentVersionWidth), `
    "Latest Version".PadRight($latestVersionWidth), `
    "Dependency Type".PadRight($dependencyTypeWidth), `
    "License".PadRight($licenseWidth), `
    "License URL"

$header | Out-File -FilePath $outputFile

###############################################################################
# CSV HEADER
###############################################################################

'"Dependency","Current Version","Latest Version","Dependency Type","License","License URL"' |
    Out-File -FilePath $csvOutputFile

###############################################################################
# Initialize hash tables
###############################################################################

$licenseInfo = @{}
$outputEntries = @{}

###############################################################################
# Read sbom-licenses.txt
###############################################################################

try {

    Get-Content -Path $licensesFile | ForEach-Object {

        $line = $_.Trim()

        if ($line -eq "") {
            return
        }

        # Skip header/separator lines
        if ($line -like "*Reference*" -or $line -like "*----*") {
            return
        }

        $line = $line.TrimStart('|').TrimEnd('|').Trim()

        $parts = $line -split '\s*\|\s*'

        if ($parts.Length -eq 4) {

            $dependency = $parts[0].Trim()
            $version = $parts[1].Trim()
            $license = $parts[2].Trim()
            $licenseUrl = $parts[3].Trim()

            if (-not $licenseInfo.ContainsKey($dependency)) {

                $licenseInfo[$dependency] = @{
                    Version    = $version
                    License    = $license
                    LicenseUrl = $licenseUrl
                }

            }
            else {

                Write-Output "Duplicate entry found for ${dependency} in ${licensesFile}."

            }

        }
        else {

            Write-Output "Skipping invalid line in ${licensesFile}: ${line}"

        }

    }

}
catch {

    Write-Error "Error reading ${licensesFile}: $_"

}

###############################################################################
# Read formatted_dependencies.txt
#
# This file is generated by get-details-2.sh and already contains:
#
#   Dependency
#   Current Version
#   Latest Version
#   Dependency Type
#
# Latest Version comes directly from the NuGet API.
###############################################################################

$headerSkipped = $false

try {

    Get-Content -Path $dependenciesFile | ForEach-Object {

        $line = $_.Trim()

        if ($line -eq "") {
            return
        }

        #######################################################################
        # Skip header
        #######################################################################

        if (-not $headerSkipped) {

            $headerSkipped = $true
            return

        }

        #######################################################################
        # Split into exactly 4 columns
        #######################################################################

        $fields = $line -split '\s+', 4

        if ($fields.Length -ge 4) {

            $depTrimmed = $fields[0].Trim()
            $currentVersion = $fields[1].Trim()
            $latestVersion = $fields[2].Trim()
            $dependencyType = $fields[3].Trim()

            ###################################################################
            # Prevent duplicates
            ###################################################################

            if ($outputEntries.ContainsKey($depTrimmed)) {
                return
            }

            ###################################################################
            # Get license information
            ###################################################################

            if ($licenseInfo.ContainsKey($depTrimmed)) {

                $licenseData = $licenseInfo[$depTrimmed]

                $license = $licenseData.License
                $licenseUrl = $licenseData.LicenseUrl

            }
            else {

                $license = "N/A"
                $licenseUrl = "N/A"

            }

            ###################################################################
            # Write TXT
            ###################################################################

            $outputLine = "{0}{1}{2}{3}{4}{5}" -f `
                $depTrimmed.PadRight($dependencyWidth), `
                $currentVersion.PadRight($currentVersionWidth), `
                $latestVersion.PadRight($latestVersionWidth), `
                $dependencyType.PadRight($dependencyTypeWidth), `
                $license.PadRight($licenseWidth), `
                $licenseUrl

            $outputLine | Out-File -FilePath $outputFile -Append

            ###################################################################
            # Write CSV
            ###################################################################

            $csvLine = '"{0}","{1}","{2}","{3}","{4}","{5}"' -f `
                $depTrimmed.Replace('"', '""'), `
                $currentVersion.Replace('"', '""'), `
                $latestVersion.Replace('"', '""'), `
                $dependencyType.Replace('"', '""'), `
                $license.Replace('"', '""'), `
                $licenseUrl.Replace('"', '""')

            $csvLine | Out-File -FilePath $csvOutputFile -Append

            ###################################################################
            # Mark as processed
            ###################################################################

            $outputEntries[$depTrimmed] = $true

            ###################################################################
            # Remove from licenseInfo because it has already been processed
            ###################################################################

            if ($licenseInfo.ContainsKey($depTrimmed)) {
                $licenseInfo.Remove($depTrimmed)
            }

        }
        else {

            Write-Output "Skipping invalid line in ${dependenciesFile}: ${line}"

        }

    }

}
catch {

    Write-Error "Error reading ${dependenciesFile}: $_"

}

###############################################################################
# Add remaining license entries
#
# These are license entries that were not present in formatted_dependencies.
#
# Normally this section should not be required because get-details-2.sh
# includes every dependency from dependency-report.txt.
#
# It is retained as a safety mechanism for unusual license-only entries.
###############################################################################

foreach ($depTrimmed in @($licenseInfo.Keys)) {

    if ($outputEntries.ContainsKey($depTrimmed)) {
        continue
    }

    $licenseData = $licenseInfo[$depTrimmed]

    $licenseVersion = $licenseData.Version
    $license = $licenseData.License
    $licenseUrl = $licenseData.LicenseUrl

    ###########################################################################
    # For license-only entries:
    #
    # Current Version = license report version
    # Latest Version  = N/A
    # Dependency Type = N/A
    ###########################################################################

    $dependencyType = "N/A"
    $latestVersion = "N/A"

    ###########################################################################
    # Write TXT
    ###########################################################################

    $outputLine = "{0}{1}{2}{3}{4}{5}" -f `
        $depTrimmed.PadRight($dependencyWidth), `
        $licenseVersion.PadRight($currentVersionWidth), `
        $latestVersion.PadRight($latestVersionWidth), `
        $dependencyType.PadRight($dependencyTypeWidth), `
        $license.PadRight($licenseWidth), `
        $licenseUrl

    $outputLine | Out-File -FilePath $outputFile -Append

    ###########################################################################
    # Write CSV
    ###########################################################################

    $csvLine = '"{0}","{1}","{2}","{3}","{4}","{5}"' -f `
        $depTrimmed.Replace('"', '""'), `
        $licenseVersion.Replace('"', '""'), `
        $latestVersion.Replace('"', '""'), `
        $dependencyType.Replace('"', '""'), `
        $license.Replace('"', '""'), `
        $licenseUrl.Replace('"', '""')

    $csvLine | Out-File -FilePath $csvOutputFile -Append

}
