$dependenciesFile = "formatted_dependencies.txt"
$dependenciesCsvFile = "formatted_dependencies.csv"
$licensesFile = "sbom-licenses.txt"
$outputFile = "sbom-result.txt"
$csvOutputFile = "sbom-result.csv"

# Column widths
$dependencyWidth = 50
$currentVersionWidth = 15
$latestVersionWidth = 15
$dependencyTypeWidth = 18
$licenseWidth = 25
$licenseUrlWidth = 60

###############################################################################
# TXT HEADER
###############################################################################

$header = "{0}{1}{2}{3}{4}{5}" -f `
    "Dependency".PadRight($dependencyWidth), `
    "Current Version".PadRight($currentVersionWidth), `
    "Latest Version".PadRight($latestVersionWidth), `
    "Dependency Type".PadRight($dependencyTypeWidth), `
    "License".PadRight($licenseWidth), `
    "License URL"

$header | Out-File -FilePath $outputFile

###############################################################################
# CSV HEADER
###############################################################################

'"Dependency","Current Version","Latest Version","Dependency Type","License","License URL","NUGET_VERSION"' |
    Out-File -FilePath $csvOutputFile

###############################################################################
# Initialize hash tables
###############################################################################

$licenseInfo = @{}
$outputEntries = @{}
$nugetVersionInfo = @{}

###############################################################################
# Read formatted_dependencies.csv
#
# This file is generated by get-details-2.sh and already contains:
#
# Dependency
# Current Version
# Latest Version
# Dependency Type
# NUGET_VERSION
#
###############################################################################

if (Test-Path $dependenciesCsvFile) {

    try {

        Import-Csv -Path $dependenciesCsvFile | ForEach-Object {

            $dependency = $_.Dependency

            if (-not [string]::IsNullOrWhiteSpace($dependency)) {

                $nugetVersionInfo[$dependency.Trim()] = $_.NUGET_VERSION

            }

        }

    }
    catch {

        Write-Error "Error reading ${dependenciesCsvFile}: $_"

    }

}
else {

    Write-Output "Warning: ${dependenciesCsvFile} not found. NUGET_VERSION will be N/A."

}

###############################################################################
# Read sbom-licenses.txt
###############################################################################

try {

    Get-Content -Path $licensesFile | ForEach-Object {

        $line = $_.Trim()

        if ($line -eq "") {
            return
        }

        # Skip header/separator lines
        if ($line -like "*Reference*" -or $line -like "*----*") {
            return
        }

        $line = $line.TrimStart('|').TrimEnd('|').Trim()

        $parts = $line -split '\s*\|\s*'

        if ($parts.Length -eq 4) {

            $dependency = $parts[0].Trim()
            $version = $parts[1].Trim()
            $license = $parts[2].Trim()
            $licenseUrl = $parts[3].Trim()

            if (-not $licenseInfo.ContainsKey($dependency)) {

                $licenseInfo[$dependency] = @{
                    Version    = $version
                    License    = $license
                    LicenseUrl = $licenseUrl
                }

            }
            else {

                Write-Output "Duplicate entry found for ${dependency} in ${licensesFile}."

            }

        }
        else {

            Write-Output "Skipping invalid line in ${licensesFile}: ${line}"

        }

    }

}
catch {

    Write-Error "Error reading ${licensesFile}: $_"

}

###############################################################################
# Read formatted_dependencies.txt
###############################################################################

$headerSkipped = $false

try {

    Get-Content -Path $dependenciesFile | ForEach-Object {

        $line = $_.Trim()

        if ($line -eq "") {
            return
        }

        #######################################################################
        # Skip header
        #######################################################################

        if (-not $headerSkipped) {

            $headerSkipped = $true
            return

        }

        #######################################################################
        # Split into exactly 4 columns
        #######################################################################

        $fields = $line -split '\s+', 4

        if ($fields.Length -ge 4) {

            $depTrimmed = $fields[0].Trim()
            $currentVersion = $fields[1].Trim()
            $latestVersion = $fields[2].Trim()
            $dependencyType = $fields[3].Trim()

            ###################################################################
            # Get NUGET_VERSION
            ###################################################################

            $nugetVersion = "N/A"

            if ($nugetVersionInfo.ContainsKey($depTrimmed)) {

                $nugetVersion = $nugetVersionInfo[$depTrimmed]

                if ([string]::IsNullOrWhiteSpace($nugetVersion)) {
                    $nugetVersion = "N/A"
                }

            }

            ###################################################################
            # Prevent duplicates
            ###################################################################

            if ($outputEntries.ContainsKey($depTrimmed)) {
                return
            }

            ###################################################################
            # Get license information
            ###################################################################

            if ($licenseInfo.ContainsKey($depTrimmed)) {

                $licenseData = $licenseInfo[$depTrimmed]

                $license = $licenseData.License
                $licenseUrl = $licenseData.LicenseUrl

            }
            else {

                $license = "N/A"
                $licenseUrl = "N/A"

            }

            ###################################################################
            # Write TXT
            ###################################################################

            $outputLine = "{0}{1}{2}{3}{4}{5}" -f `
                $depTrimmed.PadRight($dependencyWidth), `
                $currentVersion.PadRight($currentVersionWidth), `
                $latestVersion.PadRight($latestVersionWidth), `
                $dependencyType.PadRight($dependencyTypeWidth), `
                $license.PadRight($licenseWidth), `
                $licenseUrl

            $outputLine | Out-File -FilePath $outputFile -Append

            ###################################################################
            # Write CSV
            ###################################################################

            $csvLine = '"{0}","{1}","{2}","{3}","{4}","{5}","{6}"' -f `
                $depTrimmed.Replace('"', '""'), `
                $currentVersion.Replace('"', '""'), `
                $latestVersion.Replace('"', '""'), `
                $dependencyType.Replace('"', '""'), `
                $license.Replace('"', '""'), `
                $licenseUrl.Replace('"', '""'), `
                $nugetVersion.Replace('"', '""')

            $csvLine | Out-File -FilePath $csvOutputFile -Append

            ###################################################################
            # Mark as processed
            ###################################################################

            $outputEntries[$depTrimmed] = $true

            ###################################################################
            # Remove from licenseInfo because it has already been processed
            ###################################################################

            if ($licenseInfo.ContainsKey($depTrimmed)) {
                $licenseInfo.Remove($depTrimmed)
            }

        }
        else {

            Write-Output "Skipping invalid line in ${dependenciesFile}: ${line}"

        }

    }

}
catch {

    Write-Error "Error reading ${dependenciesFile}: $_"

}

###############################################################################
# Add remaining license entries
#
# These are packages that were not present in outdated-dependencies.txt.
# Therefore:
#
#   Current Version = license report version
#   Latest Version  = N/A
#   Dependency Type = Direct/Transitive if available from dependency report
###############################################################################

foreach ($depTrimmed in @($licenseInfo.Keys)) {

    if ($outputEntries.ContainsKey($depTrimmed)) {
        continue
    }

    $licenseData = $licenseInfo[$depTrimmed]

    $licenseVersion = $licenseData.Version
    $license = $licenseData.License
    $licenseUrl = $licenseData.LicenseUrl

    ###########################################################################
    # Get NUGET_VERSION
    ###########################################################################

    $nugetVersion = "N/A"

    if ($nugetVersionInfo.ContainsKey($depTrimmed)) {

        $nugetVersion = $nugetVersionInfo[$depTrimmed]

        if ([string]::IsNullOrWhiteSpace($nugetVersion)) {
            $nugetVersion = "N/A"
        }

    }

    ###########################################################################
    # For license-only entries, determine type from dependency report.
    #
    # get-details-2.sh now puts every dependency into formatted_dependencies,
    # so normally this section should be reached only for unusual license-only
    # entries.
    #
    # Use N/A instead of falsely claiming Unknown.
    ###########################################################################

    $dependencyType = "N/A"
    $latestVersion = "N/A"

    ###########################################################################
    # Write TXT
    ###########################################################################

    $outputLine = "{0}{1}{2}{3}{4}{5}" -f `
        $depTrimmed.PadRight($dependencyWidth), `
        $licenseVersion.PadRight($currentVersionWidth), `
        $latestVersion.PadRight($latestVersionWidth), `
        $dependencyType.PadRight($dependencyTypeWidth), `
        $license.PadRight($licenseWidth), `
        $licenseUrl

    $outputLine | Out-File -FilePath $outputFile -Append

    ###########################################################################
    # Write CSV
    ###########################################################################

    $csvLine = '"{0}","{1}","{2}","{3}","{4}","{5}","{6}"' -f `
        $depTrimmed.Replace('"', '""'), `
        $licenseVersion.Replace('"', '""'), `
        $latestVersion.Replace('"', '""'), `
        $dependencyType.Replace('"', '""'), `
        $license.Replace('"', '""'), `
        $licenseUrl.Replace('"', '""'), `
        $nugetVersion.Replace('"', '""')

    $csvLine | Out-File -FilePath $csvOutputFile -Append

}
